title: Kết Quả Đợt Tuyển Gen 1.5 Của CLB The Tech Lab
show_downloads: false
google_analytics:
theme: jekyll-theme-time-machine
github:
another_url: another value
 zip_url: https://www.facebook.com/thetechlab.2022
